apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mm
  namespace: mm

spec:
  rules:
    - host: dev.trianglestream.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  mm-svc
                port:
                  number: 5000
